name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Upload Android APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      working-directory: mobile/android
      run: chmod +x gradlew

    - name: Build with Gradle
      working-directory: mobile/android
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: mobile/android/app/build/outputs/apk/release/app-release.apk
